name: TestRepositoryDispatch

on:
  repository_dispatch:
    types: test_repository_dispatch

jobs:
  test_repository_dispatch:
    
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo

    steps:
          
    - name: Set Variable
      id: var
      run: |
        NOW=$(date +"%Y%m%d%H%M%S")
        echo ::set-output name=now::${NOW}
        
    - name: echo
      run: |
        echo "now=${{ steps.var.outputs.now }}"
        
    - name: if
      if: github.event.client_payload.test == ''
      run: |
        echo "undefined"
