name: TestRepositoryDispatch

on:
  repository_dispatch:
    types: test_repository_dispatch

jobs:
  test_repository_dispatch:
    
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo

    steps:
  
    - name: Set Ref
      id: ref
      run: |
        echo ::set-output name=ref::${{ ( github.event.client_payload.commit_sha != '' && github.event.client_payload.commit_sha ) || 'master' }}

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.ref.outputs.ref }}
        fetch-depth: 1
        
    - name: echo
      run: |
        echo "now=${{ github.sha }}"
